In [2]:
# source: https://github.com/Nixtla/nixtla

In [7]:
import pandas as pd
import os

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/electricity-short.csv')
df

     unique_id                   ds          y
0           BE  2016-12-01 00:00:00  72.000000
1           BE  2016-12-01 01:00:00  65.800000
2           BE  2016-12-01 02:00:00  59.990000
3           BE  2016-12-01 03:00:00  50.690000
4           BE  2016-12-01 04:00:00  52.580000
...        ...                  ...        ...
3595       PJM  2018-12-23 19:00:00  32.461970
3596       PJM  2018-12-23 20:00:00  32.052179
3597       PJM  2018-12-23 21:00:00  27.632347
3598       PJM  2018-12-23 22:00:00  24.746053
3599       PJM  2018-12-23 23:00:00  23.333499

[3600 rows x 3 columns]

In [8]:
from nixtlats import NixtlaClient
nixtla = NixtlaClient(
    # defaults to os.environ.get("NIXTLA_API_KEY")
    api_key = 'vGgi9lsf7E4HYwJSnz2m34nAWRO5STxS9hHMJbptSNSmTqMtTylXEEsjNpe8RerEp8Ao02gRzhfJxGi5f2J4OQCgWI6JIIEBMqoTNRNUnrP930rAnmqwwihyLuwgTeo7RYhQSCpJyw5bWVVUddki8l8a1Qh2AH9GITPNlABbOQuX6atPVNSYanYCedXcl8VjbyprosRVhPwFkn0JsN73FKb1VBGGESyaLb8ZMsyGBhUMCfY7M17kkKIrZP2sdc2a'
)
fcst_df = nixtla.forecast(df, h=24, level=[80, 90])

INFO:nixtlats.nixtla_client:Validating inputs...
INFO:nixtlats.nixtla_client:Preprocessing dataframes...
INFO:nixtlats.nixtla_client:Inferred freq: H
INFO:nixtlats.nixtla_client:Restricting input...
INFO:nixtlats.nixtla_client:Calling Forecast Endpoint...

In [9]:
fcst_df

,unique_id,ds,TimeGPT,TimeGPT-lo-90,TimeGPT-lo-80,TimeGPT-hi-80,TimeGPT-hi-90
0,BE,2016-12-31 00:00:00,46.151176,36.660475,38.337019,53.965334,55.641878
1,BE,2016-12-31 01:00:00,42.426601,31.602235,33.976728,50.876475,53.250968
2,BE,2016-12-31 02:00:00,40.242889,30.439970,33.634985,46.850794,50.045809
3,BE,2016-12-31 03:00:00,38.265339,26.841481,31.022096,45.508582,49.689197
4,BE,2016-12-31 04:00:00,36.618801,18.541384,27.981348,45.256255,54.696218
...,...,...,...,...,...,...,...
115,PJM,2018-12-24 19:00:00,33.906281,25.888781,28.286537,39.526024,41.923780
116,PJM,2018-12-24 20:00:00,32.277691,19.209136,26.466909,38.088473,45.346245
117,PJM,2018-12-24 21:00:00,28.901901,12.943889,20.403637,37.400165,44.859913
118,PJM,2018-12-24 22:00:00,25.873131,11.192260,22.315501,29.430761,40.554001
119,PJM,2018-12-24 23:00:00,23.881409,1.066460,17.272584,30.490234,46.696357